services:
  - type: web
    name: your-api-name
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: >
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn config.wsgi:application --workers 2 --threads 2
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: your-db-name
          property: connectionString
      - key: DJANGO_ALLOWED_HOSTS
        value: .onrender.com
    autoDeploy: true

databases:
  - name: your-db-name
    plan: free
    ipAllowList: []