services:
  - type: web
    name: wapu-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: >
      python manage.py migrate --noinput &&
      python manage.py collectstatic --noinput &&
      gunicorn config.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: wapu-db-api
          property: connectionString
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com,wapu-api.onrender.com"
    autoDeploy: true

databases:
  - name: wapu-db-api
    plan: free
    ipAllowList: []