services:
  - type: web
    name: wapu-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: >
      python manage.py migrate --noinput &&
      python manage.py collectstatic --noinput &&
      uvicorn config.asgi:application --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: COINGECKO_API_KEY
        sync: false
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: wapu_db_api
          property: connectionString
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com,wapu-api.onrender.com"
    autoDeploy: true

databases:
  - name: wapu_db_api
    plan: free
    ipAllowList: []